/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HilfeRouteImport } from './routes/hilfe'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as MitmachenRouteImport } from './routes/mitmachen'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TopActRouteImport } from './routes/top-act'
import { Route as AuthRueckkehrRouteImport } from './routes/auth.rueckkehr'
import { Route as CheckoutReturnRouteImport } from './routes/checkout_.return'
import { Route as KuenstlerIdRouteImport } from './routes/kuenstler.$id'
import { Route as RechtlichesDocRouteImport } from './routes/rechtliches.$doc'
import { Route as TortenIndexRouteImport } from './routes/torten.index'
import { Route as TortenIdRouteImport } from './routes/torten.$id'
import { Route as TortenAnbietenRouteImport } from './routes/torten.anbieten'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HilfeRoute = HilfeRouteImport.update({
  id: '/hilfe',
  path: '/hilfe',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const MitmachenRoute = MitmachenRouteImport.update({
  id: '/mitmachen',
  path: '/mitmachen',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TopActRoute = TopActRouteImport.update({
  id: '/top-act',
  path: '/top-act',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRueckkehrRoute = AuthRueckkehrRouteImport.update({
  id: '/auth/rueckkehr',
  path: '/auth/rueckkehr',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout_/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const KuenstlerIdRoute = KuenstlerIdRouteImport.update({
  id: '/kuenstler/$id',
  path: '/kuenstler/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RechtlichesDocRoute = RechtlichesDocRouteImport.update({
  id: '/rechtliches/$doc',
  path: '/rechtliches/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const TortenIndexRoute = TortenIndexRouteImport.update({
  id: '/torten/',
  path: '/torten/',
  getParentRoute: () => rootRouteImport,
} as any)
const TortenIdRoute = TortenIdRouteImport.update({
  id: '/torten/$id',
  path: '/torten/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TortenAnbietenRoute = TortenAnbietenRouteImport.update({
  id: '/torten/anbieten',
  path: '/torten/anbieten',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anmelden': typeof AnmeldenRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/hilfe': typeof HilfeRoute
  '/konto': typeof KontoRoute
  '/mitmachen': typeof MitmachenRoute
  '/portal': typeof PortalRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top-act': typeof TopActRoute
  '/auth/rueckkehr': typeof AuthRueckkehrRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/kuenstler/$id': typeof KuenstlerIdRoute
  '/rechtliches/$doc': typeof RechtlichesDocRoute
  '/torten/$id': typeof TortenIdRoute
  '/torten/anbieten': typeof TortenAnbietenRoute
  '/torten/': typeof TortenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anmelden': typeof AnmeldenRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/hilfe': typeof HilfeRoute
  '/konto': typeof KontoRoute
  '/mitmachen': typeof MitmachenRoute
  '/portal': typeof PortalRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top-act': typeof TopActRoute
  '/auth/rueckkehr': typeof AuthRueckkehrRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/kuenstler/$id': typeof KuenstlerIdRoute
  '/rechtliches/$doc': typeof RechtlichesDocRoute
  '/torten/$id': typeof TortenIdRoute
  '/torten/anbieten': typeof TortenAnbietenRoute
  '/torten': typeof TortenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anmelden': typeof AnmeldenRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/hilfe': typeof HilfeRoute
  '/konto': typeof KontoRoute
  '/mitmachen': typeof MitmachenRoute
  '/portal': typeof PortalRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top-act': typeof TopActRoute
  '/auth/rueckkehr': typeof AuthRueckkehrRoute
  '/checkout_/return': typeof CheckoutReturnRoute
  '/kuenstler/$id': typeof KuenstlerIdRoute
  '/rechtliches/$doc': typeof RechtlichesDocRoute
  '/torten/$id': typeof TortenIdRoute
  '/torten/anbieten': typeof TortenAnbietenRoute
  '/torten/': typeof TortenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anmelden'
    | '/blog'
    | '/checkout'
    | '/dashboard'
    | '/hilfe'
    | '/konto'
    | '/mitmachen'
    | '/portal'
    | '/shop'
    | '/sitemap.xml'
    | '/top-act'
    | '/auth/rueckkehr'
    | '/checkout/return'
    | '/kuenstler/$id'
    | '/rechtliches/$doc'
    | '/torten/$id'
    | '/torten/anbieten'
    | '/torten/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anmelden'
    | '/blog'
    | '/checkout'
    | '/dashboard'
    | '/hilfe'
    | '/konto'
    | '/mitmachen'
    | '/portal'
    | '/shop'
    | '/sitemap.xml'
    | '/top-act'
    | '/auth/rueckkehr'
    | '/checkout/return'
    | '/kuenstler/$id'
    | '/rechtliches/$doc'
    | '/torten/$id'
    | '/torten/anbieten'
    | '/torten'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anmelden'
    | '/blog'
    | '/checkout'
    | '/dashboard'
    | '/hilfe'
    | '/konto'
    | '/mitmachen'
    | '/portal'
    | '/shop'
    | '/sitemap.xml'
    | '/top-act'
    | '/auth/rueckkehr'
    | '/checkout_/return'
    | '/kuenstler/$id'
    | '/rechtliches/$doc'
    | '/torten/$id'
    | '/torten/anbieten'
    | '/torten/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnmeldenRoute: typeof AnmeldenRoute
  BlogRoute: typeof BlogRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  HilfeRoute: typeof HilfeRoute
  KontoRoute: typeof KontoRoute
  MitmachenRoute: typeof MitmachenRoute
  PortalRoute: typeof PortalRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopActRoute: typeof TopActRoute
  AuthRueckkehrRoute: typeof AuthRueckkehrRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  KuenstlerIdRoute: typeof KuenstlerIdRoute
  RechtlichesDocRoute: typeof RechtlichesDocRoute
  TortenIdRoute: typeof TortenIdRoute
  TortenAnbietenRoute: typeof TortenAnbietenRoute
  TortenIndexRoute: typeof TortenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hilfe': {
      id: '/hilfe'
      path: '/hilfe'
      fullPath: '/hilfe'
      preLoaderRoute: typeof HilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitmachen': {
      id: '/mitmachen'
      path: '/mitmachen'
      fullPath: '/mitmachen'
      preLoaderRoute: typeof MitmachenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-act': {
      id: '/top-act'
      path: '/top-act'
      fullPath: '/top-act'
      preLoaderRoute: typeof TopActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/rueckkehr': {
      id: '/auth/rueckkehr'
      path: '/auth/rueckkehr'
      fullPath: '/auth/rueckkehr'
      preLoaderRoute: typeof AuthRueckkehrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/return': {
      id: '/checkout_/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuenstler/$id': {
      id: '/kuenstler/$id'
      path: '/kuenstler/$id'
      fullPath: '/kuenstler/$id'
      preLoaderRoute: typeof KuenstlerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtliches/$doc': {
      id: '/rechtliches/$doc'
      path: '/rechtliches/$doc'
      fullPath: '/rechtliches/$doc'
      preLoaderRoute: typeof RechtlichesDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torten/': {
      id: '/torten/'
      path: '/torten'
      fullPath: '/torten/'
      preLoaderRoute: typeof TortenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torten/$id': {
      id: '/torten/$id'
      path: '/torten/$id'
      fullPath: '/torten/$id'
      preLoaderRoute: typeof TortenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torten/anbieten': {
      id: '/torten/anbieten'
      path: '/torten/anbieten'
      fullPath: '/torten/anbieten'
      preLoaderRoute: typeof TortenAnbietenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnmeldenRoute: AnmeldenRoute,
  BlogRoute: BlogRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  HilfeRoute: HilfeRoute,
  KontoRoute: KontoRoute,
  MitmachenRoute: MitmachenRoute,
  PortalRoute: PortalRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopActRoute: TopActRoute,
  AuthRueckkehrRoute: AuthRueckkehrRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  KuenstlerIdRoute: KuenstlerIdRoute,
  RechtlichesDocRoute: RechtlichesDocRoute,
  TortenIdRoute: TortenIdRoute,
  TortenAnbietenRoute: TortenAnbietenRoute,
  TortenIndexRoute: TortenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
