/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HilfeRouteImport } from './routes/hilfe'
import { Route as IndexnowKeyDottxtRouteImport } from './routes/indexnow-key[.]txt'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MitmachenRouteImport } from './routes/mitmachen'
import { Route as PasswortNeuRouteImport } from './routes/passwort-neu'
import { Route as PasswortVergessenRouteImport } from './routes/passwort-vergessen'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TopActRouteImport } from './routes/top-act'
import { Route as UeberShowlyRouteImport } from './routes/ueber-showly'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as WieFunktioniertShowlyRouteImport } from './routes/wie-funktioniert-showly'
import { Route as ApiCheckinRouteImport } from './routes/api.checkin'
import { Route as ApiStatusRouteImport } from './routes/api.status'
import { Route as ApiTaeglichRouteImport } from './routes/api.taeglich'
import { Route as AuthRueckkehrRouteImport } from './routes/auth.rueckkehr'
import { Route as BuchenIndexRouteImport } from './routes/buchen.index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout_.return'
import { Route as KuenstlerIdRouteImport } from './routes/kuenstler.$id'
import { Route as RatgeberIndexRouteImport } from './routes/ratgeber.index'
import { Route as RatgeberSlugRouteImport } from './routes/ratgeber.$slug'
import { Route as RechtlichesDocRouteImport } from './routes/rechtliches.$doc'
import { Route as TortenIndexRouteImport } from './routes/torten.index'
import { Route as TortenIdRouteImport } from './routes/torten.$id'
import { Route as TortenAnbietenRouteImport } from './routes/torten.anbieten'
import { Route as ApiKalenderTokenRouteImport } from './routes/api.kalender.$token'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as BuchenLeistungStadtRouteImport } from './routes/buchen.$leistung.$stadt'
import { Route as ApiBildKindIdRouteImport } from './routes/api.bild.$kind.$id'
import { Route as KuenstlerStadtKategorieNameRouteImport } from './routes/kuenstler.$stadt.$kategorie.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HilfeRoute = HilfeRouteImport.update({
  id: '/hilfe',
  path: '/hilfe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexnowKeyDottxtRoute = IndexnowKeyDottxtRouteImport.update({
  id: '/indexnow-key.txt',
  path: '/indexnow-key.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MitmachenRoute = MitmachenRouteImport.update({
  id: '/mitmachen',
  path: '/mitmachen',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortNeuRoute = PasswortNeuRouteImport.update({
  id: '/passwort-neu',
  path: '/passwort-neu',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortVergessenRoute = PasswortVergessenRouteImport.update({
  id: '/passwort-vergessen',
  path: '/passwort-vergessen',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TopActRoute = TopActRouteImport.update({
  id: '/top-act',
  path: '/top-act',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberShowlyRoute = UeberShowlyRouteImport.update({
  id: '/ueber-showly',
  path: '/ueber-showly',
  getParentRoute: () => rootRouteImport,
} as any)
const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const WieFunktioniertShowlyRoute = WieFunktioniertShowlyRouteImport.update({
  id: '/wie-funktioniert-showly',
  path: '/wie-funktioniert-showly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckinRoute = ApiCheckinRouteImport.update({
  id: '/api/checkin',
  path: '/api/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaeglichRoute = ApiTaeglichRouteImport.update({
  id: '/api/taeglich',
  path: '/api/taeglich',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRueckkehrRoute = AuthRueckkehrRouteImport.update({
  id: '/auth/rueckkehr',
  path: '/auth/rueckkehr',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchenIndexRoute = BuchenIndexRouteImport.update({
  id: '/buchen/',
  path: '/buchen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout_/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const KuenstlerIdRoute = KuenstlerIdRouteImport.update({
  id: '/kuenstler/$id',
  path: '/kuenstler/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberIndexRoute = RatgeberIndexRouteImport.update({
  id: '/ratgeber/',
  path: '/ratgeber/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberSlugRoute = RatgeberSlugRouteImport.update({
  id: '/ratgeber/$slug',
  path: '/ratgeber/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RechtlichesDocRoute = RechtlichesDocRouteImport.update({
  id: '/rechtliches/$doc',
  path: '/rechtliches/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const TortenIndexRoute = TortenIndexRouteImport.update({
  id: '/torten/',
  path: '/torten/',
  getParentRoute: () => rootRouteImport,
} as any)
const TortenIdRoute = TortenIdRouteImport.update({
  id: '/torten/$id',
  path: '/torten/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TortenAnbietenRoute = TortenAnbietenRouteImport.update({
  id: '/torten/anbieten',
  path: '/torten/anbieten',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKalenderTokenRoute = ApiKalenderTokenRouteImport.update({
  id: '/api/kalender/$token',
  path: '/api/kalender/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchenLeistungStadtRoute = BuchenLeistungStadtRouteImport.update({
  id: '/buchen/$leistung/$stadt',
  path: '/buchen/$leistung/$stadt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBildKindIdRoute = ApiBildKindIdRouteImport.update({
  id: '/api/bild/$kind/$id',
  path: '/api/bild/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KuenstlerStadtKategorieNameRoute =
  KuenstlerStadtKategorieNameRouteImport.update({
    id: '/kuenstler/$stadt/$kategorie/$name',
    path: '/kuenstler/$stadt/$kategorie/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anmelden': typeof AnmeldenRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/hilfe': typeof HilfeRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/konto': typeof KontoRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mitmachen': typeof MitmachenRoute
  '/passwort-neu': typeof PasswortNeuRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/portal': typeof PortalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top-act': typeof TopActRoute
  '/ueber-showly': typeof UeberShowlyRoute
  '/widerruf': typeof WiderrufRoute
  '/wie-funktioniert-showly': typeof WieFunktioniertShowlyRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/api/status': typeof ApiStatusRoute
  '/api/taeglich': typeof ApiTaeglichRoute
  '/auth/rueckkehr': typeof AuthRueckkehrRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/kuenstler/$id': typeof KuenstlerIdRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/rechtliches/$doc': typeof RechtlichesDocRoute
  '/torten/$id': typeof TortenIdRoute
  '/torten/anbieten': typeof TortenAnbietenRoute
  '/buchen/': typeof BuchenIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/torten/': typeof TortenIndexRoute
  '/api/kalender/$token': typeof ApiKalenderTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/buchen/$leistung/$stadt': typeof BuchenLeistungStadtRoute
  '/api/bild/$kind/$id': typeof ApiBildKindIdRoute
  '/kuenstler/$stadt/$kategorie/$name': typeof KuenstlerStadtKategorieNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anmelden': typeof AnmeldenRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/hilfe': typeof HilfeRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/konto': typeof KontoRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mitmachen': typeof MitmachenRoute
  '/passwort-neu': typeof PasswortNeuRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/portal': typeof PortalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top-act': typeof TopActRoute
  '/ueber-showly': typeof UeberShowlyRoute
  '/widerruf': typeof WiderrufRoute
  '/wie-funktioniert-showly': typeof WieFunktioniertShowlyRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/api/status': typeof ApiStatusRoute
  '/api/taeglich': typeof ApiTaeglichRoute
  '/auth/rueckkehr': typeof AuthRueckkehrRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/kuenstler/$id': typeof KuenstlerIdRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/rechtliches/$doc': typeof RechtlichesDocRoute
  '/torten/$id': typeof TortenIdRoute
  '/torten/anbieten': typeof TortenAnbietenRoute
  '/buchen': typeof BuchenIndexRoute
  '/ratgeber': typeof RatgeberIndexRoute
  '/torten': typeof TortenIndexRoute
  '/api/kalender/$token': typeof ApiKalenderTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/buchen/$leistung/$stadt': typeof BuchenLeistungStadtRoute
  '/api/bild/$kind/$id': typeof ApiBildKindIdRoute
  '/kuenstler/$stadt/$kategorie/$name': typeof KuenstlerStadtKategorieNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anmelden': typeof AnmeldenRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/hilfe': typeof HilfeRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/konto': typeof KontoRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mitmachen': typeof MitmachenRoute
  '/passwort-neu': typeof PasswortNeuRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/portal': typeof PortalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top-act': typeof TopActRoute
  '/ueber-showly': typeof UeberShowlyRoute
  '/widerruf': typeof WiderrufRoute
  '/wie-funktioniert-showly': typeof WieFunktioniertShowlyRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/api/status': typeof ApiStatusRoute
  '/api/taeglich': typeof ApiTaeglichRoute
  '/auth/rueckkehr': typeof AuthRueckkehrRoute
  '/checkout_/return': typeof CheckoutReturnRoute
  '/kuenstler/$id': typeof KuenstlerIdRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/rechtliches/$doc': typeof RechtlichesDocRoute
  '/torten/$id': typeof TortenIdRoute
  '/torten/anbieten': typeof TortenAnbietenRoute
  '/buchen/': typeof BuchenIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/torten/': typeof TortenIndexRoute
  '/api/kalender/$token': typeof ApiKalenderTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/buchen/$leistung/$stadt': typeof BuchenLeistungStadtRoute
  '/api/bild/$kind/$id': typeof ApiBildKindIdRoute
  '/kuenstler/$stadt/$kategorie/$name': typeof KuenstlerStadtKategorieNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anmelden'
    | '/blog'
    | '/checkout'
    | '/dashboard'
    | '/hilfe'
    | '/indexnow-key.txt'
    | '/konto'
    | '/llms.txt'
    | '/mitmachen'
    | '/passwort-neu'
    | '/passwort-vergessen'
    | '/portal'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/top-act'
    | '/ueber-showly'
    | '/widerruf'
    | '/wie-funktioniert-showly'
    | '/api/checkin'
    | '/api/status'
    | '/api/taeglich'
    | '/auth/rueckkehr'
    | '/checkout/return'
    | '/kuenstler/$id'
    | '/ratgeber/$slug'
    | '/rechtliches/$doc'
    | '/torten/$id'
    | '/torten/anbieten'
    | '/buchen/'
    | '/ratgeber/'
    | '/torten/'
    | '/api/kalender/$token'
    | '/api/stripe/webhook'
    | '/buchen/$leistung/$stadt'
    | '/api/bild/$kind/$id'
    | '/kuenstler/$stadt/$kategorie/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anmelden'
    | '/blog'
    | '/checkout'
    | '/dashboard'
    | '/hilfe'
    | '/indexnow-key.txt'
    | '/konto'
    | '/llms.txt'
    | '/mitmachen'
    | '/passwort-neu'
    | '/passwort-vergessen'
    | '/portal'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/top-act'
    | '/ueber-showly'
    | '/widerruf'
    | '/wie-funktioniert-showly'
    | '/api/checkin'
    | '/api/status'
    | '/api/taeglich'
    | '/auth/rueckkehr'
    | '/checkout/return'
    | '/kuenstler/$id'
    | '/ratgeber/$slug'
    | '/rechtliches/$doc'
    | '/torten/$id'
    | '/torten/anbieten'
    | '/buchen'
    | '/ratgeber'
    | '/torten'
    | '/api/kalender/$token'
    | '/api/stripe/webhook'
    | '/buchen/$leistung/$stadt'
    | '/api/bild/$kind/$id'
    | '/kuenstler/$stadt/$kategorie/$name'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anmelden'
    | '/blog'
    | '/checkout'
    | '/dashboard'
    | '/hilfe'
    | '/indexnow-key.txt'
    | '/konto'
    | '/llms.txt'
    | '/mitmachen'
    | '/passwort-neu'
    | '/passwort-vergessen'
    | '/portal'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/top-act'
    | '/ueber-showly'
    | '/widerruf'
    | '/wie-funktioniert-showly'
    | '/api/checkin'
    | '/api/status'
    | '/api/taeglich'
    | '/auth/rueckkehr'
    | '/checkout_/return'
    | '/kuenstler/$id'
    | '/ratgeber/$slug'
    | '/rechtliches/$doc'
    | '/torten/$id'
    | '/torten/anbieten'
    | '/buchen/'
    | '/ratgeber/'
    | '/torten/'
    | '/api/kalender/$token'
    | '/api/stripe/webhook'
    | '/buchen/$leistung/$stadt'
    | '/api/bild/$kind/$id'
    | '/kuenstler/$stadt/$kategorie/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnmeldenRoute: typeof AnmeldenRoute
  BlogRoute: typeof BlogRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  HilfeRoute: typeof HilfeRoute
  IndexnowKeyDottxtRoute: typeof IndexnowKeyDottxtRoute
  KontoRoute: typeof KontoRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MitmachenRoute: typeof MitmachenRoute
  PasswortNeuRoute: typeof PasswortNeuRoute
  PasswortVergessenRoute: typeof PasswortVergessenRoute
  PortalRoute: typeof PortalRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopActRoute: typeof TopActRoute
  UeberShowlyRoute: typeof UeberShowlyRoute
  WiderrufRoute: typeof WiderrufRoute
  WieFunktioniertShowlyRoute: typeof WieFunktioniertShowlyRoute
  ApiCheckinRoute: typeof ApiCheckinRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiTaeglichRoute: typeof ApiTaeglichRoute
  AuthRueckkehrRoute: typeof AuthRueckkehrRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  KuenstlerIdRoute: typeof KuenstlerIdRoute
  RatgeberSlugRoute: typeof RatgeberSlugRoute
  RechtlichesDocRoute: typeof RechtlichesDocRoute
  TortenIdRoute: typeof TortenIdRoute
  TortenAnbietenRoute: typeof TortenAnbietenRoute
  BuchenIndexRoute: typeof BuchenIndexRoute
  RatgeberIndexRoute: typeof RatgeberIndexRoute
  TortenIndexRoute: typeof TortenIndexRoute
  ApiKalenderTokenRoute: typeof ApiKalenderTokenRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  BuchenLeistungStadtRoute: typeof BuchenLeistungStadtRoute
  ApiBildKindIdRoute: typeof ApiBildKindIdRoute
  KuenstlerStadtKategorieNameRoute: typeof KuenstlerStadtKategorieNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hilfe': {
      id: '/hilfe'
      path: '/hilfe'
      fullPath: '/hilfe'
      preLoaderRoute: typeof HilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexnow-key.txt': {
      id: '/indexnow-key.txt'
      path: '/indexnow-key.txt'
      fullPath: '/indexnow-key.txt'
      preLoaderRoute: typeof IndexnowKeyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitmachen': {
      id: '/mitmachen'
      path: '/mitmachen'
      fullPath: '/mitmachen'
      preLoaderRoute: typeof MitmachenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-neu': {
      id: '/passwort-neu'
      path: '/passwort-neu'
      fullPath: '/passwort-neu'
      preLoaderRoute: typeof PasswortNeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-vergessen': {
      id: '/passwort-vergessen'
      path: '/passwort-vergessen'
      fullPath: '/passwort-vergessen'
      preLoaderRoute: typeof PasswortVergessenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-act': {
      id: '/top-act'
      path: '/top-act'
      fullPath: '/top-act'
      preLoaderRoute: typeof TopActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-showly': {
      id: '/ueber-showly'
      path: '/ueber-showly'
      fullPath: '/ueber-showly'
      preLoaderRoute: typeof UeberShowlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wie-funktioniert-showly': {
      id: '/wie-funktioniert-showly'
      path: '/wie-funktioniert-showly'
      fullPath: '/wie-funktioniert-showly'
      preLoaderRoute: typeof WieFunktioniertShowlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkin': {
      id: '/api/checkin'
      path: '/api/checkin'
      fullPath: '/api/checkin'
      preLoaderRoute: typeof ApiCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/taeglich': {
      id: '/api/taeglich'
      path: '/api/taeglich'
      fullPath: '/api/taeglich'
      preLoaderRoute: typeof ApiTaeglichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/rueckkehr': {
      id: '/auth/rueckkehr'
      path: '/auth/rueckkehr'
      fullPath: '/auth/rueckkehr'
      preLoaderRoute: typeof AuthRueckkehrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchen/': {
      id: '/buchen/'
      path: '/buchen'
      fullPath: '/buchen/'
      preLoaderRoute: typeof BuchenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/return': {
      id: '/checkout_/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuenstler/$id': {
      id: '/kuenstler/$id'
      path: '/kuenstler/$id'
      fullPath: '/kuenstler/$id'
      preLoaderRoute: typeof KuenstlerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/': {
      id: '/ratgeber/'
      path: '/ratgeber'
      fullPath: '/ratgeber/'
      preLoaderRoute: typeof RatgeberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/$slug': {
      id: '/ratgeber/$slug'
      path: '/ratgeber/$slug'
      fullPath: '/ratgeber/$slug'
      preLoaderRoute: typeof RatgeberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtliches/$doc': {
      id: '/rechtliches/$doc'
      path: '/rechtliches/$doc'
      fullPath: '/rechtliches/$doc'
      preLoaderRoute: typeof RechtlichesDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torten/': {
      id: '/torten/'
      path: '/torten'
      fullPath: '/torten/'
      preLoaderRoute: typeof TortenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torten/$id': {
      id: '/torten/$id'
      path: '/torten/$id'
      fullPath: '/torten/$id'
      preLoaderRoute: typeof TortenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torten/anbieten': {
      id: '/torten/anbieten'
      path: '/torten/anbieten'
      fullPath: '/torten/anbieten'
      preLoaderRoute: typeof TortenAnbietenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kalender/$token': {
      id: '/api/kalender/$token'
      path: '/api/kalender/$token'
      fullPath: '/api/kalender/$token'
      preLoaderRoute: typeof ApiKalenderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchen/$leistung/$stadt': {
      id: '/buchen/$leistung/$stadt'
      path: '/buchen/$leistung/$stadt'
      fullPath: '/buchen/$leistung/$stadt'
      preLoaderRoute: typeof BuchenLeistungStadtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bild/$kind/$id': {
      id: '/api/bild/$kind/$id'
      path: '/api/bild/$kind/$id'
      fullPath: '/api/bild/$kind/$id'
      preLoaderRoute: typeof ApiBildKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuenstler/$stadt/$kategorie/$name': {
      id: '/kuenstler/$stadt/$kategorie/$name'
      path: '/kuenstler/$stadt/$kategorie/$name'
      fullPath: '/kuenstler/$stadt/$kategorie/$name'
      preLoaderRoute: typeof KuenstlerStadtKategorieNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnmeldenRoute: AnmeldenRoute,
  BlogRoute: BlogRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  HilfeRoute: HilfeRoute,
  IndexnowKeyDottxtRoute: IndexnowKeyDottxtRoute,
  KontoRoute: KontoRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MitmachenRoute: MitmachenRoute,
  PasswortNeuRoute: PasswortNeuRoute,
  PasswortVergessenRoute: PasswortVergessenRoute,
  PortalRoute: PortalRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopActRoute: TopActRoute,
  UeberShowlyRoute: UeberShowlyRoute,
  WiderrufRoute: WiderrufRoute,
  WieFunktioniertShowlyRoute: WieFunktioniertShowlyRoute,
  ApiCheckinRoute: ApiCheckinRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiTaeglichRoute: ApiTaeglichRoute,
  AuthRueckkehrRoute: AuthRueckkehrRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  KuenstlerIdRoute: KuenstlerIdRoute,
  RatgeberSlugRoute: RatgeberSlugRoute,
  RechtlichesDocRoute: RechtlichesDocRoute,
  TortenIdRoute: TortenIdRoute,
  TortenAnbietenRoute: TortenAnbietenRoute,
  BuchenIndexRoute: BuchenIndexRoute,
  RatgeberIndexRoute: RatgeberIndexRoute,
  TortenIndexRoute: TortenIndexRoute,
  ApiKalenderTokenRoute: ApiKalenderTokenRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  BuchenLeistungStadtRoute: BuchenLeistungStadtRoute,
  ApiBildKindIdRoute: ApiBildKindIdRoute,
  KuenstlerStadtKategorieNameRoute: KuenstlerStadtKategorieNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
